name: workflow
on:
  push:
    branches: [ "main" ]
env:
  cloud: google-cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: hii
        run: |
           echo "$greeting $cloud ${{ github.repository	}}"
           echo "$greeting $cloud ${{ secrets.pro_user }}"
      
      
    

